name: civic_reporter
description: A civic reporting mobile app for reporting local issues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  
  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # HTTP & Networking
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  flutter_local_notifications: ^16.3.0
  
  # Maps (optional)
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  
  # Location
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets are handled via mock data and network images
  # No local assets needed for this app
